# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 21:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('juego_id', models.AutoField(primary_key=True, serialize=False)),
                ('juego', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad_maxima', models.IntegerField()),
                ('cantidad_usuarios', models.IntegerField()),
                ('es_publica', models.BooleanField(default=0)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='groupthree.Juego')),
            ],
        ),
        migrations.CreateModel(
            name='SalaUsuario',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
