# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupthree', '0001_groupthree_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupthree.Juego'),
        ),
    ]
