# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupthree', '0004_sala_usuario_organizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='cantidad_usuarios',
            field=models.IntegerField(default=0),
        ),
    ]
