# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupthree', '0006_remove_sala_juego'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salausuario',
            old_name='sala_id',
            new_name='sala_usuario_id',
        ),
        migrations.AddField(
            model_name='salausuario',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groupthree.Sala'),
            preserve_default=False,
        ),
    ]
