# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupthree', '0007_auto_20180130_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaJuego',
            fields=[
                ('sala_usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groupthree.Juego')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupthree.Sala')),
            ],
        ),
    ]
